FROM ZFS as akmods_zfs
FROM SOURCE_IMAGE as spamtagger-bootc

ARG IMAGE_VERSION_ARG
ARG KERNEL_NAME_ARG
#ifdef CI_SETX
ARG CI=1
#endif /* CI_SETX */

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/01-common.sh"
#ifdef PLUS
#include "build_files/spamtagger-plus/02-centos.sh"
#else 
#include "build_files/spamtagger/02-centos.sh"
#endif /* PLUS */
ostree container commit
RUNEOF

COPY build_files/github-release-install.sh /run/build_files/
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#ifdef PLUS
#include "build_files/spamtagger-plus/10-base-packages.sh"
#else 
#include "build_files/spamtagger/10-base-packages.sh"
#endif /* PLUS */
ostree container commit
RUNEOF

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=bind,from=akmods_zfs,source=/kernel-rpms,dst=/tmp/kernel-rpms \
    bash <<'RUNEOF'
#include "build_files/11-base-kernel-swap.sh"
ostree container commit
RUNEOF

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=bind,from=akmods_zfs,src=/rpms,dst=/tmp/akmods-zfs-rpms \
    bash <<'RUNEOF'
#include "build_files/12-base-zfs.sh"
ostree container commit
RUNEOF

#ifdef CENTOS
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/centos/12-base-kmods.sh"
ostree container commit
RUNEOF
#endif /* CENTOS */

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/13-base-configurations.sh"
ostree container commit
RUNEOF

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/98-cleanup.sh"
ostree container commit
RUNEOF

RUN bash <<'RUNEOF'
#include "build_files/99-finalize.sh"
RUNEOF

RUN ["bootc", "container", "lint", "--fatal-warnings", "--no-truncate"]
