FROM SOURCE_IMAGE as spamtagger-bootc

ARG IMAGE_VERSION_ARG
#ifdef CI_SETX
ARG CI=1
#endif /* CI_SETX */

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/01-common.sh"
ostree container commit
RUNEOF

COPY build_files/github-release-install.sh /run/build_files/
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#ifdef PLUS
#include "build_files/spamtagger-plus/10-packages.sh"
#else
#include "build_files/spamtagger/10-packages.sh"
#endif /* PLUS */
ostree container commit
RUNEOF

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/13-base-configurations.sh"
#ifdef PLUS
#include "build_files/spamtagger-plus/13-configuration.sh"
#else
#include "build_files/spamtagger/13-configuration.sh"
#endif /* PLUS */
ostree container commit
RUNEOF

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=tmpfs,dst=/var/tmp \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
#include "build_files/98-cleanup.sh"
ostree container commit
RUNEOF

RUN bash <<'RUNEOF'
#include "build_files/99-finalize.sh"
RUNEOF

RUN ["bootc", "container", "lint", "--fatal-warnings", "--no-truncate"]
