[[customizations.user]]
name = "root"
password = "STPassw0rd"
key = "<SSHPUBKEY>"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "4 GiB"

[[customizations.filesystem]]
mountpoint = "/etc/spamtagger"
minsize = "100 MiB"

[[customizations.filesystem]]
mountpoint = "/var/spamtagger"
minsize = "10 GiB"
