name: Container Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # daily at 4am

jobs:
  debsecan-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest container
        id: pull
        run: |
          docker pull ghcr.io/spamtagger/spamtagger-bootc:spamtagger-13

      - name: Install debsecan
        id: install
        run: |
          docker run --name=debsecan \
            -t ghcr.io/spamtagger/spamtagger-bootc:spamtagger-13 \
            bash -c "apt-get update && apt-get install -y debsecan"
          
      - name: Run and parse debsecan
        id: parse
        run: |
          docker start debsecan \
            "debsecan --suite trixie --format detail --only-fixed" > vulns
          echo count=$(cat vulns | wc -l) >> $GITHUB_OUTPUT

      - name: Open GitHub Issue if vulnerabilities found
        id: create-issue
        if: steps.parse.outputs.count != '0'
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: "${{ steps.parse.outputs.count }} vulnerabilities detected in spamtagger-bootc:spamtagger-13"
          content-filepath: vulns
          labels: security, automated
          token: ${{ secrets.GITHUB_TOKEN }}
