name: Container Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # daily at 4am

jobs:
  debsecan-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest container
        id: pull
        run: |
          docker pull ghcr.io/spamtagger/spamtagger-bootc:spamtagger-13

      - name: Install and run debsecan
        id: scan
        run: |
          docker run --name=debsecan \
            -t ghcr.io/spamtagger/spamtagger-bootc:spamtagger-13 \
            bash -c "/usr/spamtagger/tools/security_scan.sh" > vulns
          echo count=$(cat vulns | wc -l) >> $GITHUB_OUTPUT
          
      - name: Open GitHub Issue if vulnerabilities found
        id: create-issue
        if: steps.scan.outputs.count != '0'
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: "${{ steps.scan.outputs.count }} vulnerabilities detected in spamtagger-bootc:spamtagger-13"
          content-filepath: vulns
          labels: security, automated
          token: ${{ secrets.GITHUB_TOKEN }}
